# Generated by Django 5.2.1 on 2025-05-22 07:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='任务编号')),
                ('name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('proposer', models.CharField(max_length=5, verbose_name='提出者')),
                ('proposed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提出日期')),
                ('details', models.TextField(verbose_name='任务详情')),
                ('expected_completion_date', models.DateField(verbose_name='期望完成日期')),
                ('executor', models.CharField(max_length=5, verbose_name='执行人')),
                ('project', models.CharField(max_length=50, verbose_name='所属项目')),
                ('related_object_code', models.CharField(help_text='前三个字符为"REQ"或"RIS"', max_length=7, verbose_name='所属需求/风险编码')),
                ('related_name', models.CharField(blank=True, max_length=50, verbose_name='所属需求/风险名称')),
                ('participants', models.CharField(help_text='多个参与人用逗号分隔', max_length=50, verbose_name='参与人')),
                ('parent_task', models.CharField(blank=True, max_length=7, null=True, verbose_name='父任务')),
                ('status', models.CharField(choices=[('PENDING', '待开始'), ('IN_PROGRESS', '进行中'), ('ON_HOLD', '已暂缓'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], default='PENDING', max_length=11, verbose_name='任务状态')),
                ('priority', models.CharField(choices=[('P0', 'P0 - 最高优先级'), ('P1', 'P1 - 高优先级'), ('P2', 'P2 - 中优先级'), ('P3', 'P3 - 低优先级')], default='P2', max_length=2, verbose_name='优先级')),
                ('deliverable_location', models.CharField(blank=True, max_length=255, verbose_name='交付物存放位置')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务清单',
                'ordering': ['-proposed_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=8, unique=True, verbose_name='进度编号')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('progress_description', models.TextField(max_length=500, verbose_name='进度说明')),
                ('related_object_code', models.CharField(help_text='根据所在页面自动填入', max_length=7, verbose_name='所属需求/任务/风险/项目编码')),
                ('related_type', models.CharField(choices=[('REQ', '需求'), ('TASK', '任务'), ('RISK', '风险'), ('PROJECT', '项目')], default='TASK', max_length=7, verbose_name='关联类型')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_tracks', to='tasks.task')),
            ],
            options={
                'verbose_name': '进度跟踪',
                'verbose_name_plural': '进度跟踪',
                'ordering': ['-update_date'],
            },
        ),
    ]
