# Generated by Django 5.2.1 on 2025-05-27 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='related_name',
            new_name='related_object_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_completion_date',
            field=models.DateField(null=True, verbose_name='期望完成日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='proposed_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提出日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, editable=False, max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='任务编号'),
        ),
    ]
