# Generated by Django 5.2.1 on 2025-05-27 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_related_name_task_related_object_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresstracking',
            name='related_object_code',
        ),
        migrations.RemoveField(
            model_name='progresstracking',
            name='related_type',
        ),
        migrations.AlterField(
            model_name='progresstracking',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_trackings', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('P0', 'P0 - 资源优先保障，限时完成'), ('P1', 'P1 - 排入当月计划'), ('P2', 'P2 - 纳入后续月份'), ('P3', 'P3 - 暂缓实施')], default='P2', max_length=2, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='task',
            name='proposed_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='提出日期'),
        ),
    ]
