# Generated by Django 5.2.1 on 2025-06-12 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_progresstracking_related_object_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deliverable_location',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_object_code',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_object_name',
        ),
        migrations.AddField(
            model_name='progresstracking',
            name='related_object_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='关联需求/任务/风险项目编码'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_code',
            field=models.CharField(blank=True, help_text='前三个字符为"REQ"或"RIS"', max_length=7, null=True, verbose_name='所属需求/风险编码'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='所属需求/风险名称'),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='任务详情'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expected_completion_date',
            field=models.DateField(verbose_name='期望完成日期'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=30, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='task',
            name='participants',
            field=models.CharField(blank=True, help_text='多个参与人用逗号分隔', max_length=50, null=True, verbose_name='参与人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(choices=[('PRJ0001', '建设FSSC(1期)'), ('PRJ0002', '建设PMS'), ('PRJ0003', '建设闲置资产管理系统'), ('PRJ0004', '香港公司切换SAP系统'), ('PRJ0005', '建设关务系统'), ('PRJ0006', '上线贸易订单转自动生产工单功能'), ('PRJ0007', '金属报表优化(3期)'), ('PRJ0008', '财务数据可视化'), ('PRJ0009', '建设动电回收物联网平台'), ('PRJ0010', '数字化规划硬仗经营分析子项目'), ('PRJ0011', '建设FSSC(2期)'), ('PRJ0012', '建设税务信息化管理平台'), ('PRJ0013', '需求管理'), ('PRJ0014', 'SAP及周边系统运维'), ('PRJ0015', 'BFS运维'), ('PRJ0016', 'BPC运维'), ('PRJ0017', 'OA运维'), ('PRJ0018', '财务信息化体系建设'), ('PRJ0019', '财经流程导入EBPM'), ('PRJ0020', '财经分授权调整'), ('PRJ0021', '其他')], max_length=7, verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='任务编号'),
        ),
    ]
