# Generated by Django 5.2.1 on 2025-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_deliverable_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.CharField(db_index=True, max_length=5, verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('P0', 'P0 - 资源优先保障，限时完成'), ('P1', 'P1 - 排入当月计划'), ('P2', 'P2 - 纳入后续月份'), ('P3', 'P3 - 暂缓实施')], db_index=True, default='P2', max_length=2, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(choices=[('PRJ0001', '建设FSSC(1期)'), ('PRJ0002', '建设PMS'), ('PRJ0003', '建设闲置资产管理系统'), ('PRJ0004', '香港公司切换SAP系统'), ('PRJ0005', '建设关务系统'), ('PRJ0006', '上线贸易订单转自动生产工单功能'), ('PRJ0007', '金属报表优化(3期)'), ('PRJ0008', '财务数据可视化'), ('PRJ0009', '建设动电回收物联网平台'), ('PRJ0010', '数字化规划硬仗经营分析子项目'), ('PRJ0011', '建设FSSC(2期)'), ('PRJ0012', '建设税务信息化管理平台'), ('PRJ0013', '需求管理'), ('PRJ0014', 'SAP及周边系统运维'), ('PRJ0015', 'BFS运维'), ('PRJ0016', 'BPC运维'), ('PRJ0017', 'OA运维'), ('PRJ0018', '财务信息化体系建设'), ('PRJ0019', '财经流程导入EBPM'), ('PRJ0020', '财经分授权调整'), ('PRJ0021', '其他')], db_index=True, max_length=7, verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', '待开始'), ('IN_PROGRESS', '进行中'), ('ON_HOLD', '已暂缓'), ('CLOSED', '已关闭'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=11, verbose_name='任务状态'),
        ),
    ]
