# Generated by Django 5.2.1 on 2025-06-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_executor_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='proposer',
            field=models.CharField(db_index=True, max_length=5, verbose_name='提出者'),
        ),
    ]
